CREATE DATABASE PROBA1
GO
USE PROBA1
GO
CREATE TABLE TABELA1
(
	T1_ID INT PRIMARY KEY IDENTITY(1,1),
	OPIS VARCHAR(50)
);
GO
CREATE TABLE TABELA2
( T2_ID INT PRIMARY KEY IDENTITY(1,1),
  OPIS CHAR(30),
  T2_FK INT,
  CONSTRAINT Tabela1_Tabela2 FOREIGN KEY(T2_FK)
  REFERENCES TABELA1(T1_ID)
);
GO