CREATE DATABASE PROCEDURA;
GO
USE PROCEDURA;
GO
CREATE TABLE Skole
(
	SKID INT IDENTITY(1,1) PRIMARY KEY ,
	Naziv CHAR(30),
	Mesto CHAR(30)
);
GO
CREATE TABLE PROFESORI
(
	PROFID INT IDENTITY(1,1) PRIMARY KEY,
	Ime CHAR(30),
	Prezime CHAR(30),
	SKID INT
	CONSTRAINT profesor_skola FOREIGN KEY(SKID) 
    REFERENCES Skole(SKID)
);
CREATE TABLE Ucenici
(
	UCID INT IDENTITY(1,1)PRIMARY KEY,
	Ime CHAR(30),
	Prezime CHAR(30),
	Razred INT,
	Odeljenje INT,
	Prosek FLOAT,
	SKID INT,
	PROFID INT
	CONSTRAINT ucenici_skola FOREIGN KEY(SKID) 
    REFERENCES Skole(SKID),
	CONSTRAINT ucenici_profesori FOREIGN KEY(PROFID) 
    REFERENCES Skole(PROFID)
);