USE FIRMA;
/*SELECT SUM(PLATA) AS PLATA_LO_PLOMO FROM RADNIK;*/
SELECT BROD ,AVG(PLATA) PROSEK FROM Radnik GROUP BY brod;
SELECT BROD ,AVG(PLATA) PROSEK FROM Radnik GROUP BY brod HAVING BROD IN(10,20);