CREATE PROCEDURE PROC_1
@ID INT,@RAZRED INT
AS
BEGIN
	SELECT UCID,IME,PREZIME,PROSEK FROM UCENICI WHERE UCID=@ID;

	SELECT NAZIV,MESTO,RAZRED,AVG(PROSEK) AS PROSEK_RAZREDA
	FROM (SKOLE S JOIN UCENICI U ON U.SKID=S.SKID)
	GROUP BY U.RAZRED,S.NAZIV,S.MESTO
	HAVING U.RAZRED=@RAZRED
	ORDER BY AVG(PROSEK) DESC;
END;