USE FIRMA;
SELECT R.IME,R.prezime FROM RADNIK AS R WHERE brod=20;
SELECT R.IME,R.prezime FROM RADNIK AS R JOIN ODELJENJE AS O 
ON R.brod=O.brod AND O.mesto='Dorcol';
SELECT * FROM RADNIK WHERE brod=(SELECT BROD FROM ODELJENJE WHERE MESTO='DORCOL');
SELECT R.IME,R.PLATA+ISNULL(R.premija,0) FROM RADNIK R WHERE 
R.POSAO=(SELECT POSAO FROM RADNIK WHERE IME='MITAR') AND R.IME!='MITAR';


SELECT IME,PLATA,DATEPART(YEAR,datzap) FROM RADNIK 
WHERE PLATA < 
(SELECT MIN(PLATA)FROM RADNIK R JOIN Odeljenje O ON R.brod=O.brod AND O.imeod='DIREKCIJA');

SELECT IME FROM RADNIK WHERE DATZAP<= ALL (SELECT DATZAP FROM Radnik);

/* ID IME PLATU I KVAL, ZA RADNIKA KOJI IMAJU ISTU PLATU KAO I BILO KOJI ZASPOSLEN SA VISOKOM STRUCNOM SPREMOM */
SELECT IDBR,IME,PLATA,kvalif FROM RADNIK 
WHERE PLATA =ANY(SELECT PLATA FROM RADNIK WHERE KVALIF='VSS') AND KVALIF!='VSS'; 

SELECT IDBR,IME,PLATA FROM RADNIK R
WHERE PLATA >= ALL(SELECT MAX(PLATA) FROM RADNIK GROUP BY BROD);
